---
parser: "babel-eslint"

extends: "eslint:recommended"

env:
  amd: true
  browser: true
  commonjs: true
  embertest: true
  es6: true
  jasmine: true
  jest: true
  jquery: true
  mocha: true
  mongo: true
  node: true
  phantomjs: true
  protractor: true
  qunit: true
  serviceworker: true
  webextensions: true
  worker: true

rules:
  # 多行分割时要求保留最后一项的分割逗号
  comma-dangle:
    - 1
    - "always-multiline"

  # 除了 null 之外，必须使用带类型判定的等于
  eqeqeq:
    - 2
    - "allow-null"

  # 文件末尾需要空行
  eol-last: 1

  # 键值对之间允许超过一个的空格（用于对齐）
  key-spacing:
    - 1
    - align: "value"

  # 变量声明和模块导入声明允许超过一个的空格（用于对齐）
  no-multi-spaces:
    - 1
    -
      exceptions:
        VariableDeclarator: true
        ImportDeclaration: true

  # 该有分号的地方必须有
  semi:
    - 2
    - "always"
